language: rust

rust:
  - stable
  - nightly

env:
  # Tests the u32 backend
  - TEST_COMMAND=test EXTRA_FLAGS='--no-default-features' FEATURES='std u32_backend'
  # Tests the u64 backend
  - TEST_COMMAND=test EXTRA_FLAGS='--no-default-features' FEATURES='std u64_backend'
  # Tests the avx2 backend
  - TEST_COMMAND=test EXTRA_FLAGS='--no-default-features' FEATURES='std avx2_backend'
  # Tests serde support and default feature selection
  - TEST_COMMAND=test EXTRA_FLAGS='' FEATURES='serde'
  # Tests building without std. We have to select a backend, so we select the one
  # most likely to be useful in an embedded environment.
  - TEST_COMMAND=build EXTRA_FLAGS='--no-default-features' FEATURES='u32_backend'
  # Tests no_std+alloc usage using the most embedded-friendly backend
  - TEST_COMMAND=test EXTRA_FLAGS='--lib --no-default-features' FEATURES='alloc u32_backend'

matrix:
  exclude:
    # Test the avx2 backend only on nightly
    - rust: stable
      env: TEST_COMMAND=test EXTRA_FLAGS='--no-default-features' FEATURES='std avx2_backend'
    # Test no_std+alloc only on nightly
    - rust: stable
      env: TEST_COMMAND=test EXTRA_FLAGS='--lib --no-default-features' FEATURES='alloc u32_backend'

script:
  - cargo $TEST_COMMAND --features="$FEATURES" $EXTRA_FLAGS

notifications:
  slack:
    rooms:
      - dalek-cryptography:Xxv9WotKYWdSoKlgKNqXiHoD#dalek-bots
