name: Cross

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-D warnings'

jobs:

  test-cross:
    name: Test
    strategy:
      matrix:
        include:
          # ARM32
          - target: armv7-unknown-linux-gnueabihf
            rust: stable

          # ARM64
          - target: aarch64-unknown-linux-gnu
            rust: stable

          # PPC32
          - target: powerpc-unknown-linux-gnu
            rust: stable

    # TODO: We only test x/ed/curve for cross as derive is platform specifics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ${{ matrix.deps }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - uses: RustCrypto/actions/cross-install@master
      - run: cross test -p curve25519-dalek --release --target ${{ matrix.target }}
      - run: cross test -p ed25519-dalek --release --target ${{ matrix.target }}
      - run: cross test -p x25519-dalek --release --target ${{ matrix.target }}
